name: Checkmarx AST Scan
on:
  push:
    branches:      
      - master
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@main #Github Action version
        with:
          project_name: Webgoat_GithubAction
          cx_tenant: ${{ secrets.CX_TENANT }}
          base_uri: ${{ secrets.BASE_URI }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          scan_types:  ${{ secrets.SCAN_TYPES }}
