name: Checkmarx AST Scan
on:
  push:
    branches:      
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          project_name: Webgoat_GithubAction
          cx_tenant: smaguilarcx
          base_uri: https://eu.ast.checkmarx.net # https://ast-master.dev.cxast.net #
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          scan_types: sast,kics,sca
